### ISSUE TITLE
Project name on the "Item to order" report

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#16]
What is the situation with adding the name of the project that used the last item on the excel spreadsheet for items to order?

**Comment by kjthoward** [comment]
Got something that mostly works there's just one small, maybe problem with it...

Because things are decremented from the amount left in stock by the date opened I am finding the item that was open most recently and taking the project from that. The issue comes where if two items where opened on the same day for different projects (not sure how likely this is to happen in practice though) then because the date used for two items is the same, it will only show one project if they are different so it might not actually be the true last user. Does that make sense? And does it seem ok?

**Comment by FlaviaMS** [comment]
I makes some sense. Just to clarify that one project will appear even if two open the reagent on the same day right? I don't care if it was the real last or not. I would care if it is the last if they are open in different days. Is that still going to work like that?

**Comment by kjthoward** [comment]
Yes, so for example:

### Scenario 1

| Item      | Date Open  | Project that Opened it |
|-----------|------------|------------------------|
| Buffer EB | 09/07/2020 | Project 1              |
| Buffer EB | 10/07/2020 | Project 2              |
| Buffer EB | 11/07/2020 | Project 2              |
| Buffer EB | 12/07/2020 | Project 1              |

In this Scenario, if buffer EB needed to be ordered it would show as "Project 1" as they opened used it last (on 12/07/2020)

### Scenario 2

| Item      | Date Open  | Project that Opened it |
|-----------|------------|------------------------|
| Buffer EB | 09/07/2020 | Project 1              |
| Buffer EB | 10/07/2020 | Project 2              |
| Buffer EB | 11/07/2020 | Project 2              |
| Buffer EB | 11/07/2020 | Project 2              |

In this Scenario, if buffer EB needed to be ordered it would show as "Project 2", There were two dates "last open" (11/07/2020), but they are the same project so it doesn't matter.

### Scenario 3

| Item      | Date Open  | Project that Opened it |
|-----------|------------|------------------------|
| Buffer EB | 09/07/2020 | Project 1              |
| Buffer EB | 10/07/2020 | Project 2              |
| Buffer EB | 11/07/2020 | Project 2              |
| Buffer EB | 11/07/2020 | Project 1              |

In this Scenario, if buffer EB needed to be ordered it would _still_ show as "Project 2", There were two dates "last open" (11/07/2020), but the projects are different, but because of the way the sorting works it takes the first instance if there are two dates the same.

Does that all seem ok?

**Comment by FlaviaMS** [comment]
It seems perfect to me. I shall close this issue =D

**Comment by kjthoward** [comment]
Reopened as this issue is not close as the feature has not yet been implemented.

**Comment by FlaviaMS** [comment]
Sorry I got too confident XD
