### ISSUE TITLE
Total number of pages in PDF reports

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#25]
According to UKAS guidelines we need to have the total number of pages on the PDF reports.
Example.
We now have just page 1, but it should be page 1 of 3, for example.
Can this be added?

**Comment by kjthoward** [comment]
Probably, I can look later

**Comment by kjthoward** [comment]
This was fixed in 65c3b98

**Comment by FlaviaMS** [comment]
I think there is a problem with the numbering.

![image](https://user-images.githubusercontent.com/65717277/88650680-d8557980-d0c0-11ea-8041-25acb8ea1185.png)

**Comment by kjthoward** [comment]
What report exactly did you get that on? I tested it one reports with 1, 2 and 18 pages and they all showed the correct numbers

**Comment by FlaviaMS** [comment]
I got it from an All Items In Stock Report

**Comment by kjthoward** [comment]
Which one... Please be specific and include the exact steps that caused an issue when reporting an issue. "All Items" could be one of several things:

![image](https://user-images.githubusercontent.com/40895027/88652397-b230d900-d0c2-11ea-8a69-8eca841fa7b2.png)

4/5 of those include the word "All"

**Comment by FlaviaMS** [comment]
Yes they all they "all, but only one is "all in stock items". It is the second from the bottom.

**Comment by kjthoward** [comment]
Seems to work fine for me...

![image](https://user-images.githubusercontent.com/40895027/88652890-4ac75900-d0c3-11ea-8a48-526f8645c426.png)
![image](https://user-images.githubusercontent.com/40895027/88652904-4e5ae000-d0c3-11ea-976b-75bbbed7255c.png)

**Comment by FlaviaMS** [comment]
I still have it wrong. I can check in anotehr computer later on and let you know if it is a local problem.

**Comment by kjthoward** [comment]
Found it, I think... 

For me the issue was on the "All Unvalidated Items" report. 

I think it was to do with how the report page numbers were counted:
Essentially because when the script makes each page it doesn't know the total number of pages, I made it make the report once with a placeholder value, that's why "of 1" part. Then once the report is made it counts the number of pages and remakes the report but replaces the "of 1" part with "of <X>" where X is the total number of pages it counted. So I think sometimes it was returning the first copy of the report (the one it makes with all "of 1" pages to count the number of total pages). 

I've changed some stuff around so it should always give you the correct version, but let me know if it still shows up.

**Comment by FlaviaMS** [comment]
It's worse now. I hae no titles/headers or footers on any of the "Inventory reports".

![image](https://user-images.githubusercontent.com/65717277/88654974-ff627a00-d0c5-11ea-822c-d0d4f145d2cd.png)

**Comment by FlaviaMS** [comment]
It actually seems to be on all PDF reports. Or at leasdt the ones I tested "reagents" and "project".

**Comment by kjthoward** [comment]
Very odd as they all look totally fine to me... 

Going to totally re-do how it calculates page numbers (basically as it looks like each page can have 29 rows of data I can just see how many times 29 goes into the number of rows and use that for the page number).

Give me 5 mins...

**Comment by FlaviaMS** [comment]
Sorry I just had time to check now. It seems to be working very well now. 
Thanks
