### ISSUE TITLE
Deactivated reagents still show up

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#28]
Hey,

I deactivated a reagent before I ever put any on the database. The reagent is High volume Core tips 8racks/box.
Then created the new reagents I want with its final name.
However, Both still appear on the fron page. The one I added the reagetn too and the one I deactivated.
I thought deactivated stuff you disappear. Is that the case?

![image](https://user-images.githubusercontent.com/65717277/88690287-66e2ee80-d0f3-11ea-9517-d5ddbf7d5fa8.png)

**Comment by kjthoward** [comment]
No, if you deactivate anything (supplier, reagent, project) it just removes it from any dropdown selection.

So deactivating a supplier removes it from:

- Selecting a default supplier when adding a new item
- Selecting a supplier when booking in a new item

Deactivating a reagent removes it from:

- The list of items you can pick when booking something in

Deactivating a Project removes it from:

- The list of Projects when booking something in
- The list of Projects when you open an item

It doesn't remove/hide anything anywhere else as, for example. If you added "Buffer EB" and have 5 of them in stock, but then you decide to not use/buy any more of that and deactivate it you still have those 5 in stock so it shows up on the database sumary page (which is where I assume that picture is from) but no one else will be able to book in any more "Buffer EB".

Does that make sense/answer your question? If you'd prefer I can make it so that deactivated items don't show up on the summary page, though if you want that I'd suggest (if it's possible I'll need to look) that it only doesn't show deactivated items if there are none in stock, as you might still have some in stock to use up, just not want any more to be ordered (like I said above)

**Comment by FlaviaMS** [comment]
Yes please if it is possible to make them disapeear that would be great. I noticed the item in question also shows up on the "Item to order report"
![image](https://user-images.githubusercontent.com/65717277/88692554-191bb580-d0f6-11ea-92c7-a6e41a712750.png)

I think that coull cause great confusion. Do you think they can be removed from that list also. If not add to the list their status maybe.

**Comment by kjthoward** [comment]
The reason it's on the reports is for the similar reason, you might still have them instock to use up but you are discontinuing that reagent so want to remove it from the list of things people can book in.

Do these changes sound ok?

- If an item is deactivated AND its current stock level is 0 it will be hidden on the summary page
- If an item is deactivated AND its current stock level is 0 it will be hidden in the "Select Reagent to Generate Stock Report For" dropdown
- If an item is deactivated it won't show up at all on the "items to order" report (This should have been done already but was missed...)

I don't think any of the "Inventory Reports" will need changing as they only show things that are in stock anyway. So if an item is deactivated but you still have some it should still show up on those (as you physically do have that item in stock) and if an item is deactivated but the stock count is 0 it wouldn't show up anyway as the stock count is 0

**Comment by FlaviaMS** [comment]
That sounds perfect.
Thanks
