### ISSUE TITLE
Server error related to expiry date

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#29]
First let me say I know this is a dumb problem, but I defend products to be idiot proof.
There is a servenr error 500  (for obvious reasons) when a person selects the last day of the month as 31st on months that don't have 31 days. Let's say that the 31st of September was selected this morning, for example. An error occured and we had to book the item again.

The issue is that for items that do not have a day on the expiry date, but only the month, we are expected to select the last day of the month.

Is there a way of removing the 31st as an option if the month selected before only has 30 days?
If is it too hard I will just implement the policy that the 30th is the last day of every month for this purpose.
Thanks

**Comment by kjthoward** [comment]
I guess I never thought of that as I expected people to just copy the expiry date from the box or something but yes, Idiot proof is always the best way!

There's no easy way to make the selectable values in one box depend on another (well, there might be but I don't know it!). I can look into it but for now, I think the best thing would be that instead of crashing it will give a FormValidation error next to the expiry date box. This is the same kind of error that you get if you try to save without filling in the required fields.

Does that sound ok? I can make the error message say something like "31st September 2021 is not a valid date, maximum day value is 30" or something so you can know what the last valid day is (mostly thinking this would be useful for leap years and February)

**Comment by kjthoward** [comment]
I'll need to play around with the formatting to get the box to align properly (it's currently underneath "Expiry Date" instead of to the right of it) but would you prefer something like this where you click the date instead?

![image](https://user-images.githubusercontent.com/40895027/88807978-33af6680-d1aa-11ea-8dd0-eec97ba838cd.png)

Let me know which you'd prefer:

- The same style you have now, just with an error if you pick an invalid date (with the posibility of this being changed to dynamic boxes that limit the date you can pick based on the selected month)
- Calendar style as above
- Something else you've though of

**Comment by FlaviaMS** [comment]
Sorry for the delay. It has been one of those days.
I like both suggestions, but I think the second one is more user friendly.

**Comment by kjthoward** [comment]
I've got a calendar that now words, but it doesn't look quite as good as the one above...

![image](https://user-images.githubusercontent.com/40895027/88916718-79c60200-d25e-11ea-96be-da917f65f093.png)

Is that ok? I was going to change everywhere that you enter a date (booking in, opening, validation etc...) to use the same style if you're happy with it.

**Comment by FlaviaMS** [comment]
I like how it looks and I think it might be a good change to have it everywhere.
Very good job sir!!!!

**Comment by kjthoward** [comment]
So I know this is "closed" but I had an idea that I thought might be helpful (and was also interesting to work out...).

Next to each date field, if you think it will be useful, I can add a "Reset to Today" button so that you can easily set things to today's date or go back to today's date if you accidentally select a date that's very far in the future past etc...

It can either be just a hyperlink looking thing:
![image](https://user-images.githubusercontent.com/40895027/88957142-5ae36200-d296-11ea-911b-cc1e855dd711.png)

Or a proper button (colour and style can be customised)
![image](https://user-images.githubusercontent.com/40895027/88957317-9da53a00-d296-11ea-9e11-bcee59373276.png)

Or if you have ideas for other shortcuts that might be useful I can do those, for example something like "Add 1 year to current date" etc...

**Comment by FlaviaMS** [comment]
This is an awesome Idea. For sure on the receive data a "Reset to Today" would be very helpful.
I think the idea of having a one year from today bottom next to the Expiry date.
Now just me being spoiled. Helene's rule is that any reagents without expiry dates will ave one year, but dry consumables like PCR plates would have two years. DO you think it would be feasible to have both? And more important do you think that would be more confusing for the user?

**Comment by kjthoward** [comment]
So something like this??

![image](https://user-images.githubusercontent.com/40895027/89032447-992b6080-d32c-11ea-97a5-70b031e5296a.png)

I made it date received + 1/2 years rather than today as you might not be booking something in on the day received (and if it does need to be today you can just click "Reset to Today" on the "date received" and then the button for adding 1/2 years.

Did you want any buttons (such as the "reset to today") on any other date inputs (e.g selecting date open, validated, finished etc...)?

**Comment by FlaviaMS** [comment]
I like how the buttons look and the date received thing seems good to me.
On the last topic I would say maybe..only if you see a need for it. I am under the impression all of those buttons automatically come up with "today's" date by default. Am I right? Because if that is the case I think the button might be a bit redundant no? Or you are thinking along the same lines on if by mistake we go to a very far date in the future for example?

**Comment by kjthoward** [comment]
The do, all (I think), default to todays date so it might not be necessary. It's up to you if you think they'll be useful, you're the ones going to be using it

**Comment by FlaviaMS** [comment]
Jut by thinking about it it seems that the two most useful ones are the one year and two years ones.
Would it be ok to test it for another week with the new features before deciding?

**Comment by kjthoward** [comment]
So just the buttons that are in the above picture ("Reset to today" on "Date Received" and the "...+1/2 years" for "Expiry date"), no other buttons on any other date fields??

**Comment by FlaviaMS** [comment]
Yes sir, for another week or two of routine use. Would that be ok?

**Comment by kjthoward** [comment]
Yes of course, I'll push that out now 😊

**Comment by FlaviaMS** [comment]
Thanks =D
