### ISSUE TITLE
Add project at disposing of a reagent

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#37]
Is it possible that you add the possibility to change the project also when we dispose of an item?
If so, could we make it that we can create reports based on that also?

**Comment by kjthoward** [comment]
Yes, can do. Only thing is that items that already exist won't have a value for this. If you want I can also write a small script that will go through the database and if an item is marked as finished it will set the "Final Project" (or whatever you want to call it) to be the same as the one that was set when it was opened, as a one off thing.

Also you'll need to come up with better names for them... At the moment when you select a project when opening an item it's called "Project Used". Maybe change this to "Opened by Project" and then come up with something for the one at closing too...?

**Comment by kjthoward** [comment]
So, just a typed version of what I was saying yesterday: Is it actually needed to know which project an item was booked in for, what project opened it, and what project finished it? I assumed that you wanted to know who used the majority of an item for billing purposes, e.g "Item X was booked in for project Y, but project Z used most of it so they pay for it". If that's the case do you really need who opened it? Would it just make more sense to have which project an item was booked in for, and then who used the majority of that item (which will be selected when an item is finished, defaulting to project booked in).

Let me know what you think and which way you'd rather go with it.

**Comment by FlaviaMS** [comment]
It made sense yesterday, but it makes even more now. I think ou make a very good point. Is this change easy for you to do?

**Comment by kjthoward** [comment]
Yes it's quite easy. I'll just move the form that comes up when you open something to show when you finish it instead.

What do you want to do with existing items (items that are open and have a "project used" selected"? Currently if I do nothing their "project used" will stay the same as was selected. If you want I can remove all of the "project used" for all items that have not yet been finished.

**Comment by FlaviaMS** [comment]
I am not sure I understood you question.
But if I try to reply anyway I would say that the project tat opened the item to be now the project that closed it, but the project we booked it under to remain the same.
Hope that makes sense.

**Comment by kjthoward** [comment]
Ah no, this is more what I meant:

- For items that are newly booked in (booked in after this update), they'll get a project set when they get booked in then when they get marked as Finished there'll be an option to say if a different project finished it (instead of that happening at the open stage)
- For items already booked in but not open, they'll have a project from booking in  then when they get marked as Finished there'll be an option to say if a different project finished it (instead of that happening at the open stage)
- For items already booked in AND have already been opened and had a project selected for that stage, what do you want to do for those items? My suggestion is that if they are not finished I just remove their "project used" as it will be selected when it gets marked as finished, and if they have already been marked as finished to just leave their "project used" as it is

Does that make more sense? The third bullet is the one that needs a decision made, the others were just explaining how it'll work.

**Comment by FlaviaMS** [comment]
Yes sir, this makes tons of sense now and I agree with your suggestion. Just remove the "project used".
Thanks
