### ISSUE TITLE
Size of columns on PDF reports

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#6]
Is there a way make sure all the headings are visible on a pdf report?
![image](https://user-images.githubusercontent.com/65717277/82572683-9f5acf00-9b7c-11ea-80bf-ad7a9ba6ac11.png)

Just because as you can see, because some of the reagents and suppliers have a bigger name it spreads thing around and we start to miss the columns at the beginning and end. I think it is better to lose some text on every column but be able to see them all. Hope that makes sense.
If this is problematic leave it, because the xlsx work just fine for all sizes

**Comment by kjthoward** [comment]
I thought that may happen... It's because they are sorted into columns and it tries to keep everything (headings and data) in line with each other, so because you have some long reagent names the width of that column is long and this get cut off. The only real way to fix the pdf reports is to reduce the number of columns that you have. 

Are there any that you could do without?

**Comment by FlaviaMS** [comment]
I am not sure. I would have to check this with Helene, because she might have an idea for what to use these reports that I am not aware of. 
Before I talk to her I have one more question on this. If you change the columns that appear on the pdf will it change the spread sheet?

**Comment by kjthoward** [comment]
Currently yes it will, as it gets all the data and then creates the Excel of pdf, but if that's a problem I can move it so the Excel and pdf reports have different data collection steps

**Comment by kjthoward** [comment]
Closing this one as I think it should now be all sorted as I split long items in reports to go over multiple lines in e1bbbcc9ea6fa3a55a3440bdd679732c4a78128d
